package ikev2

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/kcnc/vibe-practicum-vpn/internal/config"
)

func TestRenderServerConfigDeterministic(t *testing.T) {
	dir := t.TempDir()
	cfg := config.DefaultIKEv2Config()
	cfg.Enabled = true
	cfg.ServerName = "vpn.example.test"
	cfg.StateDir = filepath.Join(dir, "state")
	cfg.ConfigDir = filepath.Join(dir, "cfg")
	cfg.SwanctlDir = "/etc/swanctl"
	reg := NewRegistry(cfg)
	if _, err := reg.Create("zphone", "10.88.0.20", "ios"); err != nil {
		t.Fatal(err)
	}
	if _, err := reg.Create("aphone", "10.88.0.10", "ios"); err != nil {
		t.Fatal(err)
	}
	if err := reg.Revoke("zphone"); err != nil {
		t.Fatal(err)
	}
	clients, err := reg.List()
	if err != nil {
		t.Fatal(err)
	}

	files1, err := RenderServerConfig(cfg, clients)
	if err != nil {
		t.Fatal(err)
	}
	files2, err := RenderServerConfig(cfg, clients)
	if err != nil {
		t.Fatal(err)
	}
	if len(files1) != 1 || files1[0].RelativePath != "swanctl.conf" {
		t.Fatalf("unexpected files: %+v", files1)
	}
	if files1[0].Content != files2[0].Content {
		t.Fatal("render output is not deterministic")
	}
	out := files1[0].Content
	for _, want := range []string{"# Generated by vibe-vpn; deterministic non-secret server config", "ikev2-vpn {", "local_addrs = vpn.example.test", "pools = ikev2-pool", "if_id_in = 42", "if_id_out = 42", "pools {", "addrs = 10.88.0.0/24", "server_gateway = 10.88.0.1", "xfrm_interface = ipsec0", "aphone = 10.88.0.10", "# zphone = 10.88.0.20 (revoked)"} {
		if !strings.Contains(out, want) {
			t.Fatalf("render missing %q in:\n%s", want, out)
		}
	}
}

func TestRenderServerConfigRejectsUnsafeServerName(t *testing.T) {
	for _, name := range []string{
		"vpn.example.test\nconnections { injected { } }",
		"vpn.example.test; include /etc/shadow",
		"vpn.example.test`touch /tmp/pwned`",
		"vpn.example.test$(touch /tmp/pwned)",
	} {
		t.Run(name, func(t *testing.T) {
			cfg := config.DefaultIKEv2Config()
			cfg.Enabled = true
			cfg.ServerName = name
			if files, err := RenderServerConfig(cfg, nil); err == nil {
				t.Fatalf("expected unsafe server_name to fail before render, got files: %+v", files)
			}
		})
	}
}

func TestRenderServerConfigAllowsSafeServerName(t *testing.T) {
	cfg := config.DefaultIKEv2Config()
	cfg.Enabled = true
	cfg.ServerName = "vpn-1.example.test"
	files, err := RenderServerConfig(cfg, nil)
	if err != nil {
		t.Fatal(err)
	}
	out := files[0].Content
	if !strings.Contains(out, "# Server: vpn-1.example.test") || !strings.Contains(out, "local_addrs = vpn-1.example.test") {
		t.Fatalf("safe server name not rendered deterministically:\n%s", out)
	}
}

func TestWriteRenderedServerConfigWritesOnlyOutputDir(t *testing.T) {
	dir := t.TempDir()
	cfg := config.DefaultIKEv2Config()
	cfg.ServerName = "vpn.example.test"
	outDir := filepath.Join(dir, "out")
	written, err := WriteRenderedServerConfig(outDir, []RenderedFile{{RelativePath: "swanctl.conf", Content: "test\n"}})
	if err != nil {
		t.Fatal(err)
	}
	if len(written) != 1 || written[0] != filepath.Join(outDir, "swanctl.conf") {
		t.Fatalf("unexpected written: %#v", written)
	}
	b, err := os.ReadFile(written[0])
	if err != nil {
		t.Fatal(err)
	}
	if string(b) != "test\n" {
		t.Fatalf("unexpected content %q", b)
	}
}
