package ikev2

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/kcnc/vibe-practicum-vpn/internal/config"
)

type RenderedFile struct {
	RelativePath string
	Content      string
}

func RenderServerConfig(c config.IKEv2Config, clients []Client) ([]RenderedFile, error) {
	c.ApplyDefaults()
	if err := c.Validate(); err != nil {
		return nil, err
	}
	sorted := append([]Client(nil), clients...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	serverName := c.ServerName
	if serverName == "" {
		serverName = "%any"
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by vibe-vpn; deterministic non-secret server config\n")
	fmt.Fprintf(&b, "# Server: %s\n", serverName)
	fmt.Fprintf(&b, "# VPN subnet: %s\n", c.VPNSubnet)
	fmt.Fprintf(&b, "# Gateway: %s\n", c.GatewayIP)
	fmt.Fprintf(&b, "# XFRM: %s if_id=%d\n\n", c.XFRMInterface, c.XFRMIfID)
	b.WriteString("connections {\n")
	b.WriteString("  ikev2-vpn {\n")
	fmt.Fprintf(&b, "    local_addrs = %s\n", serverName)
	b.WriteString("    version = 2\n")
	b.WriteString("    proposals = aes256-sha256-modp2048\n")
	fmt.Fprintf(&b, "    pools = ikev2-pool\n")
	fmt.Fprintf(&b, "    if_id_in = %d\n", c.XFRMIfID)
	fmt.Fprintf(&b, "    if_id_out = %d\n", c.XFRMIfID)
	b.WriteString("    local {\n")
	b.WriteString("      auth = pubkey\n")
	b.WriteString("      certs = server-cert.pem\n")
	b.WriteString("    }\n")
	b.WriteString("    remote {\n")
	b.WriteString("      auth = pubkey\n")
	b.WriteString("    }\n")
	b.WriteString("    children {\n")
	b.WriteString("      ikev2-vpn {\n")
	b.WriteString("        local_ts = 0.0.0.0/0,::/0\n")
	b.WriteString("        esp_proposals = aes256-sha256-modp2048\n")
	b.WriteString("        mode = tunnel\n")
	b.WriteString("      }\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")
	b.WriteString("pools {\n")
	b.WriteString("  ikev2-pool {\n")
	fmt.Fprintf(&b, "    addrs = %s\n", c.VPNSubnet)
	b.WriteString("  }\n")
	b.WriteString("}\n\n")
	b.WriteString("vibe_vpn_metadata {\n")
	fmt.Fprintf(&b, "  server_name = %s\n", serverName)
	fmt.Fprintf(&b, "  vpn_subnet = %s\n", c.VPNSubnet)
	fmt.Fprintf(&b, "  server_gateway = %s\n", c.GatewayIP)
	fmt.Fprintf(&b, "  xfrm_interface = %s\n", c.XFRMInterface)
	fmt.Fprintf(&b, "  xfrm_if_id = %d\n", c.XFRMIfID)
	b.WriteString("  clients {\n")
	for _, cl := range sorted {
		if cl.Revoked {
			fmt.Fprintf(&b, "    # %s = %s (revoked)\n", cl.Name, cl.IP)
			continue
		}
		fmt.Fprintf(&b, "    %s = %s\n", cl.Name, cl.IP)
	}
	b.WriteString("  }\n")
	b.WriteString("}\n")
	return []RenderedFile{{RelativePath: "swanctl.conf", Content: b.String()}}, nil
}

func WriteRenderedServerConfig(outputDir string, files []RenderedFile) ([]string, error) {
	if outputDir == "" {
		return nil, fmt.Errorf("output dir is required")
	}
	var written []string
	for _, f := range files {
		if f.RelativePath == "" || filepath.IsAbs(f.RelativePath) || strings.Contains(f.RelativePath, "..") {
			return nil, fmt.Errorf("unsafe render path %q", f.RelativePath)
		}
		p := filepath.Join(outputDir, f.RelativePath)
		if err := os.MkdirAll(filepath.Dir(p), 0755); err != nil {
			return nil, err
		}
		if err := os.WriteFile(p, []byte(f.Content), 0644); err != nil {
			return nil, err
		}
		written = append(written, p)
	}
	return written, nil
}
